spring:
  application:
    name: payment-service
  config:
    import: classpath:kafka_payment_service.yml

  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce_payment?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      #ddl-auto: validate
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    #defer-datasource-initialization: true

  logging:
    level:
      org.springframework.jdbc.datasource.init: DEBUG

#  kafka:
#    bootstrap-servers: localhost:9092
#    consumer:
#      group-id: payment-group
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring.json.trusted.packages: "*"
#        spring.json.use.type.headers: true
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#      properties:
#        spring.json.add.type.headers: true

server:
  port: 8081