spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#  sql:
#    init:
#      mode: always              # always run scripts on startup
#      continue-on-error: true   # don’t fail if table exists
#      schema-locations: classpath:sql/order_service_create_table.sql

  jpa:
    hibernate:
      #ddl-auto: validate
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    #defer-datasource-initialization: true

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          order-service:
            connectTimeout: 2000      # 2 seconds to connect
            readTimeout: 3000         # 5 seconds to wait for response
            loggerLevel: full         # optional - logs request/response details

app:
  restTemplate:
    connectTimeout: 2000
    readTimeout: 3000

resilience4j:
  circuitbreaker:
    instances:
      order-service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 5
        slidingWindowType: COUNT_BASED

#        slidingWindowSize: 5                # how many recent calls are observed
#        failureRateThreshold: 50             # % of failed calls that will open the circuit
#        waitDurationInOpenState: 6s         # how long the breaker stays open before half-open test
#        permittedNumberOfCallsInHalfOpenState: 3
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        recordExceptions:
#          - feign.RetryableException
#          - java.net.SocketTimeoutException
#          - java.net.ConnectException
  retry:
    instances:
      order-service:                   # instance name must match Feign client name
        maxAttempts: 3                   # total attempts (1 initial + 2 retries)
        waitDuration: 5s                 # delay between retries
#        retryExceptions:
#          - feign.RetryableException     # retry when Feign times out
#          - java.net.SocketTimeoutException
#          - java.net.ConnectException

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics,circuitbreakerevents,retries
#  endpoint:
#    health:
#      show-details: always

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakerevents,retries
  endpoint:
    health:
      show-details: always



#management:
#  endpoints:
#    web:
#      exposure:
#        include: *

server:
  port: 8080

#logging:
#  level:
#    io.github.resilience4j.retry: DEBUG
#    io.github.resilience4j.circuitbreaker: DEBUG

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        #adds a type header (e.g. __TypeId__) into the Kafka message.
        #This tells consumers exactly what Java class the message was originally
        #(e.g. com.example.common.events.PaymentCompletedEvent).
        #This makes deserialization automatic on the consumer side.
        spring.json.add.type.headers: true
    consumer:
      #group-id: order-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        #allows deserialization of all event classes.
        #(If you want stricter control, you can instead set "com.example.common.events".)
        #Without it, Spring Kafka will throw an exception:
        #org.apache.kafka.common.errors.SerializationException:
        #Class is not in the trusted packages
        spring.json.trusted.packages: "*"
        #tells the deserializer to use the header info (sent by the producer) to pick the correct class automatically.
        spring.json.use.type.headers: true

        #✅ Important Rules
        #1. Type headers must exist
        #
        #The producer must add them:
        #
        #spring.json.add.type.headers: true
        #
        #
        #The consumer must use them:
        #
        #spring.json.use.type.headers: true
        #
        #
        #Otherwise, both listeners might get confused, or you’ll see:
        #
        #org.springframework.kafka.support.converter.ConversionException:
        #Failed to convert JSON to target type

